{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "wealthwise.namespace" . }}
  labels:
    {{- include "wealthwise.commonLabels" . | nindent 4 }}
{{- end }}
