{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wealthwise.fullname" . }}-allow-api-ingress
  namespace: {{ include "wealthwise.namespace" . }}
  labels:
    {{- include "wealthwise.commonLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wealthwise.api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "wealthwise.web.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.api.port }}
{{- end }}
