spring:
  application:
    name: finsight-mcp
  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: finsight
      auto-index-creation: true
  ai:
    mcp:
      server:
        name: finsight
        transport: STDIO # Use stdio OR sse

server:
  port: ${MCP_PORT:5100}

jwt:
  secret: ${JWT_SECRET:}

logging:
  level:
    org.springframework.ai.mcp: DEBUG
