{{- if .Values.agenticAi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finsight.fullname" . }}-agentic-ai
  namespace: {{ include "finsight.namespace" . }}
  labels:
    {{- include "finsight.agenticAi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agenticAi.service.type }}
  ports:
    - port: {{ .Values.agenticAi.port }}
      targetPort: {{ .Values.agenticAi.port }}
      protocol: TCP
  selector:
    {{- include "finsight.agenticAi.selectorLabels" . | nindent 4 }}
{{- end }}
