{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "finsight.fullname" . }}-api-pdb
  namespace: {{ include "finsight.namespace" . }}
  labels:
    {{- include "finsight.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "finsight.api.selectorLabels" . | nindent 6 }}
{{- end }}
