apiVersion: v1
kind: Service
metadata:
  name: wealthwise-web
  namespace: wealthwise
  labels:
    app.kubernetes.io/name: wealthwise-web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: wealthwise-web
